name: akwasi_awuah
description: Official Application for Akwasi Awuah

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  provider: ^6.0.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  path_provider: ^2.0.7
  package_info: ^2.0.2
  just_audio: ^0.9.18
  just_audio_background: ^0.0.1-beta.2
  flutter_platform_widgets: ^1.12.0
  fijkplayer: ^0.10.1
  url_launcher: ^6.0.17
  video_player: ^2.2.7
  store_redirect: ^2.0.0
  google_mobile_ads: ^0.13.6
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/splash.jpg
    - images/placeholder.png
    - images/background.jpg
    - images/pic_placeholder.png
    - images/logo_about.png
    - images/logo.png
    - images/contact_mail.png
    - images/donate.jpg
    - images/rightbg.png
    - images/mainbg.png